---
- name: Install, configure and run Sensu agent
  hosts: agents
  become: true

  tasks:
    - name: Install agent
      include_role:
        name: sensu.sensu_go.agent
      vars:
        version: 5.16.1
        agent_config:
          deregister: true
          keepalive-interval: 5
          keepalive-warning-timeout: 10
          subscriptions: "{{ subscriptions }}"
