version: "2.1"

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - run: echo dummy
