---
- name: Install, configure and run Sensu backend
  hosts: backends
  become: true

  tasks:
    - name: Install backend
      include_role:
        name: sensu.sensu_go.backend
      vars:
        version: 5.16.1
        cluster_admin_username: tadej
        cluster_admin_password: my.password  # USE VAULT IN REAL SCENARIOS!!!
        backend_config:
          log-level: info
